#include "FOLDER-FOR-NECESSARY-LOWERCASE-LETTERS/HEADER-FOR-GENERAL-USE.h"

DATA_TYPE FUNCTION_THAT_PRINTS_A_STRING(OTHER_DATA_TYPE* STRING);

DATA_TYPE FUNCTION_THAT_PRINTS_AN_ERROR(OTHER_DATA_TYPE* ERROR) {
    FUNCTION_THAT_PRINTS_A_STRING("ERROR RETURNED BY PROGRAM");
    FUNCTION_THAT_PRINTS_A_STRING(ERROR);
}

//COMMENT SAYING HOW GOOD THIS FUNCTION IS
DATA_TYPE POORLY_WRITTEN_ERROR_CHECKING_FUNCTION(DATA_TYPE* CHECK) {
    CONDITIONAL_WORD(CHECK == NULL) {
        FUNCTION_THAT_PRINTS_AN_ERROR("ERROR RELATED TO MEMORY ALLOCATION FALURE");
    }
}

DATA_TYPE LIBRARY_FUNCTION(DATA_TYPE FIRST_INPUT, DATA_TYPE SECOND_INPUT) {
    RETURN_DIRECTIVE FIRST_INPUT + SECOND_INPUT;
}

//PROMISE TO USE THE INPUT LATER THAT NEVER HAPPENS
DATA_TYPE SOME_OUTPUT_FUNCTION(DATA_TYPE UNUSED) {
    FUNCTION_THAT_PRINTS_A_STRING("MESSAGE");
}

DATA_TYPE FUNCTION_CURRENTLY_UNUSED() {
    RETURN_DIRECTIVE VALUE;
}

DATA_TYPE HORRIBLY_UNOPTIMISED_MATH_FUNCTION(DATA_TYPE* INPUT) {
    /* PARAGRAPGH EXPLAINING THE NUMBER SYSTEM */
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN OTHER_VALUE PLUS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN SMALL_NUMBER MINUS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN SMALL_NUMBER) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN SMALL_NUMBER PLUS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN MEDIUM_NUMBER MINUS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN MEDIUM_NUMBER) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN MEDIUM_NUMBER PLUS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN LARGE_NUMBER MINUS_SIGN OTHER_VALUE) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    CONDITIONAL_WORD(*INPUT EQUALS_SIGN LARGE_NUMBER) {
        FUNCTION_CURRENTLY_UNUSED();
    }
    // MOCKERY OF SWITCH STATEMENTS
    RETURN_DIRECTIVE *INPUT;
}