#include "FOLDER-FOR-NECESSARY-LOWERCASE-LETTERS/HEADER-FOR-GENERAL-USE.h"

DATA_TYPE FUNCTION_THAT_PRINTS_A_STRING(OTHER_DATA_TYPE* STRING);

DATA_TYPE FUNCTION_THAT_PRINTS_AN_ERROR(OTHER_DATA_TYPE* ERROR) {
    FUNCTION_THAT_PRINTS_A_STRING("ERROR RETURNED BY PROGRAM");
    FUNCTION_THAT_PRINTS_A_STRING(ERROR);
}

//COMMENT SAYING HOW GOOD THIS FUNCTION IS
DATA_TYPE POORLY_WRITTEN_ERROR_CHECKING_FUNCTION(DATA_TYPE* CHECK) {
    CONDITIONAL_WORD(CHECK == NULL) {
        FUNCTION_THAT_PRINTS_AN_ERROR("ERROR RELATED TO MEMORY ALLOCATION FALURE");
    }
}

DATA_TYPE LIBRARY_FUNCTION(DATA_TYPE FIRST_INPUT, DATA_TYPE SECOND_INPUT) {
    RETURN_DIRECTIVE FIRST_INPUT + SECOND_INPUT;
}

//PROMISE TO USE THE INPUT LATER THAT NEVER HAPPENS
DATA_TYPE SOME_OUTPUT_FUNCTION(DATA_TYPE UNUSED) {
    FUNCTION_THAT_PRINTS_A_STRING("MESSAGE");
}