
#include "FOLDER-FOR-NECESSARY-LOWERCASE-LETTERS/HEADER.h"

//COMMENT DESCRIBING THE LARGE DATA TYPE
LARGE_DATA_TYPE LARGE_DATA_TYPE_TYPE {
    DATA_TYPE NAME_THAT_DOESNT_HELP_TO_DESCRIBE_WHAT_VALUE_IS_FOR;
    OTHER_DATA_TYPE* ANOTHER_UNHELPFUL_NAME;
    DATA_TYPE* POINTER_THATS_NEVER_USED
};

//COMMENT NOT HELPING TO DESCRIBE FUNCTION
DATA_TYPE FUNCTION_NOBODY_UNDERSTANDS(LARGE_DATA_TYPE LARGE_DATA_TYPE_TYPE* FUNCTION_INPUT) {
    FUNCTION_INPUT->NAME_THAT_DOESNT_HELP_TO_DESCRIBE_WHAT_VALUE_IS_FOR = VALUE;
    *FUNCTION_INPUT->ANOTHER_UNHELPFUL_NAME = OTHER_VALUE;
    FUNCTION_INPUT->NAME_THAT_DOESNT_HELP_TO_DESCRIBE_WHAT_VALUE_IS_FOR = LIBRARY_FUNCTION(VALUE, OTHER_VALUE);
    RETURN_DIRECTIVE FUNCTION_INPUT->NAME_THAT_DOESNT_HELP_TO_DESCRIBE_WHAT_VALUE_IS_FOR;
}

DATA_TYPE FUNCTION_THAT_PRINTS_AN_ERROR(OTHER_DATA_TYPE* ERROR) {
    FUNCTION_THAT_PRINTS_A_STRING("ERROR RETURNED BY PROGRAM");
    FUNCTION_THAT_PRINTS_A_STRING(ERROR);
}

//COMMENT SAYING HOW GOOD THIS FUNCTION IS
DATA_TYPE POORLY_WRITTEN_ERROR_CHECKING_FUNCTION(DATA_TYPE* CHECK) {
    CONDITIONAL_WORD(CHECK == NULL) {
        FUNCTION_THAT_PRINTS_AN_ERROR("ERROR RELATED TO MEMORY ALLOCATION FALURE");
    }
}

//UNHELPFUL DESCRIPTION OF MAIN FUNCTION
DATA_TYPE MAIN_FUNCTION(DATA_TYPE ARGUMENT_COUNT, OTHER_DATA_TYPE** ARGUMENT_TABLE) {
    LARGE_DATA_TYPE LARGE_DATA_TYPE_TYPE* LARGE_DATA_TYPE_TYPE_NAME = FUNCTION_THAT_ALLOCATES_MEMORY(DATA_SIZE);
    POORLY_WRITTEN_ERROR_CHECKING_FUNCTION(LARGE_DATA_TYPE_TYPE_NAME);
    FUNCTION_NOBODY_UNDERSTANDS(LARGE_DATA_TYPE_TYPE_NAME);
    SOME_OUTPUT_FUNCTION(LARGE_DATA_TYPE_TYPE_NAME->NAME_THAT_DOESNT_HELP_TO_DESCRIBE_WHAT_VALUE_IS_FOR);
    RETURN_DIRECTIVE;
}




