#include "HEADER-FOR-GENERAL-USE.h"

DATA_TYPE FUNCTION_THAT_PRINTS_A_STRING(OTHER_DATA_TYPE* STRING) {
    printf(STRING);
    printf("\n");
}

DATA_TYPE FUNCTION_THAT_PRINTS_A_NUMBER(DATA_TYPE NUMBER) {
    printf("NUMBER\n");
}

THIRD_DATA_TYPE* FUNCTION_THAT_ALLOCATES_MEMORY(DATA_TYPE SIZE_OF_BUFFER) {
    return malloc(SIZE_OF_BUFFER);
}