#include <stdio.h>
#include <stdlib.h>
#define RETURN_DIRECTIVE return;
typedef int DATA_TYPE;
typedef char OTHER_DATA_TYPE;
#define LARGE_DATA_TYPE struct
#define VALUE 0
#define OTHER_VALUE 1
#define CONDITIONAL_WORD if
#define DATA_SIZE 9

DATA_TYPE FUNCTION_THAT_PRINTS_A_STRING(OTHER_DATA_TYPE* STRING) {
    printf(STRING);
}

DATA_TYPE* FUNCTION_THAT_ALLOCATES_MEMORY(DATA_TYPE SIZE_OF_BUFFER) {
    return malloc(SIZE_OF_BUFFER);
}
DATA_TYPE MAIN_FUNCTION(DATA_TYPE ARGUMENT_COUNT, OTHER_DATA_TYPE* ARGUMENT_TABLE[]);

DATA_TYPE LIBRARY_FUNCTION(DATA_TYPE FIRST_INPUT, DATA_TYPE SECOND_INPUT) {
    return FIRST_INPUT + SECOND_INPUT;
}

DATA_TYPE SOME_OUTPUT_FUNCTION(DATA_TYPE UNUSED) {
    FUNCTION_THAT_PRINTS_A_STRING("MESSAGE");
}

int main(int argc, char* argv[]) {
    return MAIN_FUNCTION(argc, argv);
}
